name: Laravel Enlightn

on:[workflow_dispatch]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Install Enlightn
      run: composer require  enlightn/enlightn --dev
    - name: Execute tests
      # run: |
      #   cp .env.example .env
      #   php artisan enlightn --ci
      #   rm .env
      run: php artisan enlightn --ci
